sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":99, \"username\":\"aaa\",\"password\":\"111\"}]"
spring:
  application:
    name: item-service
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/你的名字路径/sp-config
          searchPaths: config
          #username: your-username
          #password: your-password
            
  rabbitmq:
    host: 192.168.213.132
    port: 5672
    username: admin
    password: admin  
#server:
#  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

---
spring:
  profiles: item1
  
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002    