spring:
  application:
    name: order-service
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/你的名字路径/sp-config
          searchPaths: config
          #username: your-username
          #password: your-password
  
  rabbitmq:
    host: 192.168.213.132
    port: 5672
    username: admin
    password: admin  
server:
  port: 8201
    
eureka:
  client:
    service-url: 
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
    